#!/usr/bin/env python
# SPDX-License-Identifier: BUSL-1.1
# Copyright (c) 2026 Marek Čermák
"""Calibration script — compute similarity thresholds for the active embedding model.

Usage:
    python tests/recall_quality/calibrate.py [--mode local|remote]

Outputs thresholds.json with model-appropriate values for the test suite.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import numpy as np

from tests.recall_quality.task_clusters import CLUSTERS, NOISE_TASKS

_OUT_PATH = Path(__file__).parent / "thresholds.json"


def _cosine_sim(a: list[float], b: list[float]) -> float:
    va, vb = np.asarray(a), np.asarray(b)
    denom = np.linalg.norm(va) * np.linalg.norm(vb)
    return float(np.dot(va, vb) / denom) if denom > 0 else 0.0


def _build_embedder(mode: str):
    if mode == "remote":
        # Use OpenAI via env var
        from engramia.providers.openai import OpenAIEmbeddings

        return OpenAIEmbeddings(), "text-embedding-3-small"
    else:
        from engramia.providers.local_embeddings import LocalEmbeddings

        emb = LocalEmbeddings()
        return emb, "all-MiniLM-L6-v2"


def run_calibration(mode: str = "local") -> dict:
    embedder, model_name = _build_embedder(mode)

    # One representative task per cluster (first variant)
    cluster_ids = list(CLUSTERS.keys())
    rep_tasks = [CLUSTERS[cid][0] for cid in cluster_ids]

    print(f"Embedding {len(rep_tasks)} cluster representatives ({model_name})…")
    rep_embeddings = [embedder.embed(t) for t in rep_tasks]

    # Build 12x12 similarity matrix
    n = len(cluster_ids)
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            matrix[i, j] = _cosine_sim(rep_embeddings[i], rep_embeddings[j])

    # Intra-cluster: average pairwise sim within each cluster (using all 5 variants)
    print("Computing intra-cluster similarity (all 5 variants each)…")
    intra_sims: list[float] = []
    for cid in cluster_ids:
        tasks = CLUSTERS[cid]
        embeddings = [embedder.embed(t) for t in tasks]
        for i in range(len(tasks)):
            for j in range(i + 1, len(tasks)):
                intra_sims.append(_cosine_sim(embeddings[i], embeddings[j]))

    avg_intra = float(np.mean(intra_sims))
    min_intra = float(np.min(intra_sims))

    # Cross-cluster: off-diagonal values
    cross_sims = [matrix[i, j] for i in range(n) for j in range(n) if i != j]
    avg_cross = float(np.mean(cross_sims))
    max_cross = float(np.max(cross_sims))

    # Noise
    print(f"Computing noise similarity ({len(NOISE_TASKS)} tasks)…")
    noise_sims: list[float] = []
    for noise_task in NOISE_TASKS:
        noise_emb = embedder.embed(noise_task)
        for rep_emb in rep_embeddings:
            noise_sims.append(_cosine_sim(noise_emb, rep_emb))

    max_noise = float(np.max(noise_sims))
    avg_noise = float(np.mean(noise_sims))

    # Thresholds: conservative — give 5-10% margin
    intra_threshold = round(min_intra - 0.05, 3)  # just below worst intra sim
    cross_threshold = round(max_cross + 0.05, 3)  # just above best cross sim
    noise_threshold = round(max_noise + 0.05, 3)  # just above noisiest match

    result = {
        "_model": model_name,
        "_comment": f"Auto-generated by calibrate.py. Mode: {mode}.",
        "intra_threshold": intra_threshold,
        "cross_threshold": cross_threshold,
        "noise_threshold": noise_threshold,
        "duplicate_tier": 0.92,
        "adapt_tier": 0.70,
        "_stats": {
            "avg_intra_sim": round(avg_intra, 4),
            "min_intra_sim": round(min_intra, 4),
            "avg_cross_sim": round(avg_cross, 4),
            "max_cross_sim": round(max_cross, 4),
            "avg_noise_sim": round(avg_noise, 4),
            "max_noise_sim": round(max_noise, 4),
        },
        "_matrix": {
            "cluster_ids": cluster_ids,
            "values": matrix.round(4).tolist(),
        },
    }

    _OUT_PATH.write_text(json.dumps(result, indent=2))

    print("\n=== Calibration Results ===")
    print(f"  Model:            {model_name}")
    print(f"  Avg intra-sim:    {avg_intra:.4f}  (min: {min_intra:.4f})")
    print(f"  Avg cross-sim:    {avg_cross:.4f}  (max: {max_cross:.4f})")
    print(f"  Noise max sim:    {max_noise:.4f}")
    print(f"\n  → intra_threshold: {intra_threshold}")
    print(f"  → cross_threshold: {cross_threshold}")
    print(f"  → noise_threshold: {noise_threshold}")
    print(f"\nWritten to: {_OUT_PATH}")

    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Calibrate recall quality thresholds.")
    parser.add_argument(
        "--mode",
        choices=["local", "remote"],
        default=os.environ.get("ENGRAMIA_TEST_MODE", "local"),
        help="Embedding mode (default: local)",
    )
    args = parser.parse_args()
    run_calibration(args.mode)
